### PR TITLE
Add module name into exported function slice

### PR DESCRIPTION
**Pull request by mbutki**
Adds module name to function slices in re-exported trace file. This doesn't affect the aggregation, but make it easier for a dev to understand the re-exported trace file.

### CODE REVIEW

**Comment by lynchbomb** [comment]
The implementation looks fine. Will you address the conflicts and I'll merge.

**Comment by lynchbomb** [comment]
lets just add `modMatcher` to https://github.com/TracerBench/tracerbench/blob/master/packages/parse-profile/src/cli/analyze.ts#L36

**Comment by mbutki** [comment]
> lets just add `modMatcher` to https://github.com/TracerBench/tracerbench/blob/master/packages/parse-profile/src/cli/analyze.ts#L36

I'm not 100% sure what you mean by this. Do you mean creating the modMatcher instance inside the exportHierarchy function and having it be the return value (so that it can be used further down in the analyze function)? If so, then I would rather not. Maybe in the future the re-exported trace contains details about the aggregation result, which would require it to go at the end of the analyse function, but now we have locked it in place by making it the producer on the modMatcher instance.

**Comment by lynchbomb** [comment]
More so since cli.ts is gone; with the prior implementation ported into analyze.ts. I’m fine with the proposed implementation just calling out this needs to be ported into analyze.ts now.

**Comment by mbutki** [comment]
> More so since cli.ts is gone; with the prior implementation ported into analyze.ts. I’m fine with the proposed implementation just calling out this needs to be ported into analyze.ts now.

Got it. Sorry, I was still looking at an older version locally and missed the code relocation.

**Pull request merged**
